#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cachetools
Version  : 4.2.4
Release  : 60
URL      : https://files.pythonhosted.org/packages/d7/69/c457a860456cbf80ecc2e44ed4c201b49ec7ad124d769b71f6d0a7935dca/cachetools-4.2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/d7/69/c457a860456cbf80ecc2e44ed4c201b49ec7ad124d769b71f6d0a7935dca/cachetools-4.2.4.tar.gz
Summary  : Extensible memoizing collections and decorators
Group    : Development/Tools
License  : MIT
Requires: pypi-cachetools-license = %{version}-%{release}
Requires: pypi-cachetools-python = %{version}-%{release}
Requires: pypi-cachetools-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: cachetools
Provides: cachetools-python
Provides: cachetools-python3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
========================================================================

%package license
Summary: license components for the pypi-cachetools package.
Group: Default

%description license
license components for the pypi-cachetools package.


%package python
Summary: python components for the pypi-cachetools package.
Group: Default
Requires: pypi-cachetools-python3 = %{version}-%{release}

%description python
python components for the pypi-cachetools package.


%package python3
Summary: python3 components for the pypi-cachetools package.
Group: Default
Requires: python3-core
Provides: pypi(cachetools)

%description python3
python3 components for the pypi-cachetools package.


%prep
%setup -q -n cachetools-4.2.4
cd %{_builddir}/cachetools-4.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641421308
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cachetools
cp %{_builddir}/cachetools-4.2.4/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cachetools/ba2621bfb627fd112af69f831fbf6615957348ae
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cachetools/ba2621bfb627fd112af69f831fbf6615957348ae

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
